# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_disease_publication_trait_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
