# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('reference_assembly', models.CharField(default='', max_length=255)),
                ('chromosome', models.CharField(default='', max_length=255)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
    ]
