# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromosome',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exon',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gene',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trait',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_good_quality',
            field=models.BooleanField(default=False),
        ),
    ]
