FROM registry.novogenialab.com/notasquare-zero/images/nas-urad-api:0.1

# Install voldemort client
RUN mkdir /tmp/voldemort
RUN wget https://github.com/voldemort/voldemort/archive/release-1.10.23-cutoff.zip && \
    unzip release-1.10.23-cutoff.zip && \
    mv voldemort-* /tmp/voldemort && \
    cd /tmp/voldemort/voldemort-release-1.10.23-cutoff/clients/python && \
    python setup.py install

RUN pip install pika

ENV APP_ENV test
ADD src/www /opt/www
